-- AlterTable
ALTER TABLE "TradingConfig" ADD COLUMN IF NOT EXISTS "profitLimit" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "subPeriodDays" INTEGER,
ADD COLUMN IF NOT EXISTS "subscriptionStartDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "currentProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "totalTrades" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "profitableTrades" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "losingTrades" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastTradeDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "errorCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastError" TEXT;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "TradingConfig_isActive_idx" ON "TradingConfig"("isActive");

